sudo: required

language: cpp

compiler: gcc

env:
  - CMAKE_VERSION=cmake-3.3.2

before_install:
  # Install latest cmake
  - sudo apt-get remove cmake
  - wget http://www.cmake.org/files/v3.3/$CMAKE_VERSION.tar.gz
  - tar -xzf $CMAKE_VERSION.tar.gz
  - cd $CMAKE_VERSION
  - ./bootstrap > /dev/null
  - sudo make -j8 > /dev/null
  - sudo make install
  - cd ..
  - rm -rf $CMAKE_VERSION $CMAKE_VERSION.tar.gz
  
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

before_script:
  - cmake --version
  - $CXX --version
  - git submodule init
  - git submodule update
  - mkdir build
  - cd build

script:
  - cmake ../
  - make